version: '3.7'

services:

  angular:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'

  cypress:
    build:
      context: .
      dockerfile: cypress-ci.Dockerfile
    depends_on:
      - angular
    network_mode: 'host'      